sudo: required
services:
- docker
before_install: |
  docker pull gitlab/gitlab-runner:latest
  docker run --name gitlab-runner \
    -v "$(pwd)/config:/etc/gitlab-runner" \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    -d gitlab/gitlab-runner:latest
install: |
  sed -i "s#NAME#${TRAVIS_BRANCH}#" config/config.toml
  sed -i "s#TOKEN#$(eval echo \$GITLAB_TOKEN_${TRAVIS_BRANCH})#" config/config.toml
  sed -i "s#URL#${GITLAB_URL}#" config/config.toml
script:
- bash entrypoint.sh
